### ISSUE TITLE
Line hover colour

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.ThemeCustomizer#2]
I am trying your new beta and see it now has a theme customizer.

I am trying to find the equivalent of:

![Line Color](https://user-images.githubusercontent.com/7985331/79343576-72d0e900-7f26-11ea-86fb-23dc5a5a507d.png)

**Comment by ajtruckle** [comment]
Ah, Ok. They seem to be my major issues:

![Code](https://user-images.githubusercontent.com/7985331/79345840-8b8ece00-7f29-11ea-8e90-ef73762a92b2.png)

The hover colour (I can hardly see it).
The highlight code colour doesn't stand out enough. Unlike the legacy version:

![Code2](https://user-images.githubusercontent.com/7985331/79346127-e45e6680-7f29-11ea-9d04-887897c667e4.png)

Well, the hover didn't actually work in bbPress because of the conflict but it does work in JS v3 which is good. Just the colour that is too pale. And a suitable highlight colour that is more noticeable.

The other good thing is when you hover the mouse over the code block the small icons show at top right now. :)

The only other observation is that the line numbers black in the legacy which is more noticeable.

Can you please notify me when 4.1 is out so I can have a look? I would like to update my site officially to your beta.

**Comment by AndiDittrich** [comment]
i've just added these settings to v4

![image](https://user-images.githubusercontent.com/1474107/79348600-7f107280-7f35-11ea-81f7-5642a49d04a5.png)

------

the theme are currently not subjected to change - but you're welcome to create a pull request into the EnlighterJS repository including an enhanced colorscheme

**Comment by ajtruckle** [comment]
Thanks. I tried the current beta on my live site! And I also tried a different default theme:

Monokai:

![Code3](https://user-images.githubusercontent.com/7985331/79349344-04902480-7f2e-11ea-8acb-08768ef6bc3f.png)

Works good out of the box! When I tried a saved customized theme it did not display right. So rather than fight it I am sticking with these these.

My only issue is that I have now gone and lost my extra buttons in the TinyMCE toolbar again! That is a separate issue. Off to work now.

**Comment by AndiDittrich** [comment]
the customizer has still some bugs, the next snapshot will fix a major one.

v4 will be released today or tomorrow - the Upgrade Notice are already in place: https://enlighterjs.org/wp-v4

**Comment by AndiDittrich** [comment]
the latest dev version is available on GitHub/Master

**Comment by ajtruckle** [comment]
Cool. 
By the way, I added a simple Additional CSS bit to override the display:none for your two classes with !important to get around the bbPress bug. Do for now.
