### ISSUE TITLE
Highlight whole row with Godzilla

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.ThemeCustomizer#3]
Hi !

So I have upgraded to your latest official v4 as released this afternoon. :)

On my live website I decided to try the Theme Customizer again.

I loaded Godzilla and then customised the line number hover colours. For some reason the = characters do not show with the required background:

![CodeSample](https://user-images.githubusercontent.com/7985331/79385619-d1b35400-7f60-11ea-89f3-8648e34bf0f8.png)

**Comment by AndiDittrich** [comment]
one of the tokens has a `background-color` set - the line setting does only affect the line background not the tokens - its the intended behaviour

**Comment by ajtruckle** [comment]
> one of the tokens has a `background-color` set - the line setting does only affect the line background not the tokens - its the intended behaviour

So where in the customiser do you adjust this particular `=` background colour? I have not specifically set anything myself for any tokens and it seems odd that by default this would be the case.

**Comment by AndiDittrich** [comment]
1. use the element inspector to get the token name
2. lookup the token name within the [docs](https://github.com/EnlighterJS/documentation/blob/master/development/HighlightingEngine_and_Symbols.md)
3. change the token in the customizer

**Comment by ajtruckle** [comment]
Thank you. I reviewed those documents and located **k3**.:

![Operators](https://user-images.githubusercontent.com/7985331/79441143-ca2a9400-7fce-11ea-948b-08fe52f697c9.png)

So, I then went to update the setting in the customiser:

![Operators2](https://user-images.githubusercontent.com/7985331/79441169-d31b6580-7fce-11ea-9d60-77b25653a532.png)

But when I click **Save Changes** it reverts back to `#f0f0f0`. Is this a bug?

I still don't understand why these tokens would have a background colour anyway since none of the others do. #confused

**Comment by AndiDittrich** [comment]
set it to `none`  - you cannot "remove" settings from derived themes, you have to override them

**Comment by ajtruckle** [comment]
That work. Don't know what ramifications there would be by removing this default. Any way, it works. :)

Are you planning on showing the intended colour in a small square for any given colour setting?

**Comment by AndiDittrich** [comment]
in one of the next releases the colorpicker will come back - the default WordPress `iris` colorpicker was not suitable because it creates an instance **for each** input element which increases the page load time to `10s` 

maybe i have to change the value merging algorithm that empty fields can be used instead of overriding them

**Comment by ajtruckle** [comment]
Cool!
