### ISSUE TITLE
Setting the colours for highlighted lines

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.ThemeCustomizer#4]
Thanks for the new settings in the customizer:

![Hover](https://user-images.githubusercontent.com/7985331/79387867-4b007600-7f64-11ea-9f6d-94908343c1c0.png)

I don't know if it is just me, but it seems that the first colour is applied for all hover highlighting? If I set the last option to something obvious like `#ff0000` it doesn't seem to kick in?

**Comment by AndiDittrich** [comment]
thanks, i'll check this

**Comment by AndiDittrich** [comment]
fixed in Theme-Customizer `v2.2.0` (Enlighter `v4.2.0`)

**Comment by ajtruckle** [comment]
Cool! I look forward to your next update. :) Stay safe.
