### ISSUE TITLE
Theme Customizer Doesn't Load

### ISSUE THREAD

**Issue by noodleyness** [EnlighterJS/Plugin.ThemeCustomizer#5]
The Theme Customizer doesn't load for me... 

I selected Theme Customizer under Appearance > Theme.

Then went to Theme Customizer in the menu > select "enlighter" as Base theme > load 

And nothing happens. Am I missing something?

**Comment by AndiDittrich** [comment]
what do you expect to happen ? the css settings of the base theme should appear in the input fields of the customizer (other tabs above). not every input is filled in case the styles are not used by the theme - does this happen ?

**Comment by noodleyness** [comment]
Okay I'm so sorry I did not see those tabs above, I thought the fields would load directly below. Thanks for clearing that up!
