### ISSUE TITLE
Theme Customizer does not work for .enlighter-t-wpcustom .enlighter span

### ISSUE THREAD

**Issue by gruniversal** [EnlighterJS/Plugin.ThemeCustomizer#6]
Hello,

I am not sure if this is a bug, but I hope you can help me.

**Environment**
- WordPress 5.4
- Enlighter Plugin 4.1 (downloaded from https://downloads.wordpress.org/plugin/enlighter.4.1.0.zip)

**Story**
- previous version: 3.10, now have to update entries because of missing mocha-theme
- used theme customizer to copy monokai to wpcustom
- now trying to reduce font-size from 15px to 12px

**Example**

```
<!-- wp:enlighter/codeblock {"language":"php","theme":"wpcustom"} -->
<pre class="EnlighterJSRAW" data-enlighter-language="php" data-enlighter-theme="wpcustom" data-enlighter-highlight="" data-enlighter-linenumbers="" data-enlighter-lineoffset="" data-enlighter-title="" data-enlighter-group="">
if ($result = $mysqli->query("SELECT Name FROM City LIMIT 10")) {
    printf("Select returned %d rows.\n", $result->num_rows);
    $result->close();
}
</pre>
<!-- /wp:enlighter/codeblock -->
```

**Problem**:
- cannot find a input-field to customize this entry:
```
.enlighter-t-wpcustom .enlighter span{
	font-size: 15px;
}
```
Since all tags are span, it is not possible to change the font-size.

**Proposed solution**
- there should be a way to change font-size of span as well

Best regards,
David

**Comment by AndiDittrich** [comment]
![image](https://user-images.githubusercontent.com/1474107/79699189-31c23700-828e-11ea-83a7-f9838349abb6.png)

**Comment by gruniversal** [comment]
Hello Andi,

I tried the new version 4.2 from GitHub (master, 20.4.2020) and it works on my staging system.

Thank you for your superfast reaction! That's impressive :)

Greetings from Leipzig,
David

**Comment by gruniversal** [comment]
FYI: I wrote a script to migrate my codeblock entries from an old theme to a newer one and used it to successfully migrate from theme mocha to theme wpcustom.

It's very straightforward and only tested on my machine, but maybe someone will find it helpful:
https://gitlab.com/gruniversal/wp-enlighter-migration
