### ISSUE TITLE
Line number section - Customization possible?

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/Plugin.ThemeCustomizer#7]
Hi

Can you please tell me if this is possible:

For the line numbering component on the line can we:

1. Set the background colour (just for the line number bit).
2. Include a black vertical line on the right.

Basically I would like to customise Atomic so that the line numbers looks like a column with a different background colour and a vertical line separating the column from the code area.

Is this possible with the customiser?

**Comment by AndiDittrich** [comment]
not with the customizer. you should use a full custom theme

**Comment by ajtruckle** [comment]
OK, no worries then. :)
